language: objective-c
osx_image: xcode8.2
xcode_workspace: AppComponents.xcworkspace
xcode_scheme: Sample
before_install:

    - env
    - cd Sample
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod install --repo-update

script:

    - pod lib lint ../AppComponents.podspec --use-libraries

