platform :ios, '7.0'

workspace '../AppComponents.xcworkspace'

target 'Sample' do
    pod 'AppComponents', :path => '../'
    # pod 'ESFramework', :git => 'https://github.com/ElfSundae/ESFramework.git', :branch => 'develop'
end

