platform :ios, '7.0'

workspace "../AppComponents.xcworkspace"

target "Sample" do
    pod "ESFramework", :git => 'https://github.com/ESFramework/ESFramework.git'
    pod "FontAwesomeKit/FontAwesome", :head
    pod "AppComponents", :path => "../AppComponents.podspec"
end
